spring:
  application:
      name: pfs-enquiry
  datasource:
    url: jdbc:h2:mem:pfs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2c
  data:
    rest:
      basePath: /api
  jackson:
    serialization:
      fail-on-empty-beans: false