spring:
  profiles: pfsdev
  rest:
    basePath: /api
  content:
    fs:
      filesystem-root: ${user.home}/loans/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pfsltd@12345
    maximum-pool-size: 40
    url: jdbc:mysql://localhost:3306/pfsenquiry?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&&nullCatalogMeansCurrent=true
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      validation-timeout: 5000000
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
  data:
    rest:
      basePath: /api
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: us2.smtp.mailhostbox.com
    port: 587
    username: portal.admin@pfs-ess.com
    password: Pfs@HyyXIAn2#HyyXIAn2
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: us2.smtp.mailhostbox.com
  activiti:
    activiti5CompatibilityEnabled: true
    mail-server-host: us2.smtp.mailhostbox.com
    mail-server-port: 587
    mail-server-user-name: portal.admin@pfs-ess.com
    mail-server-password: Pfs@HyyXIAn2#HyyXIAn2
    mail-server-default-from: portal.admin@pfs-ess.com
    mail-server-use-tls: true
    database-schema-update: true
oauth:
  baseUrl: http://192.168.1.205:9999/auth
sap:
  postUrl: http://192.168.1.205:8000/sap/opu/odata/sap/ZPFS_LOAN_ENQ_PORTAL_SRV/LoanApplicationSet?sap-client=300
  baseUrl: http://192.168.1.205:8000
  serviceUri: /sap/opu/odata/sap/ZPFS_LOAN_ENQ_PORTAL_SRV/LoanApplicationSet
  client: 300
  userName: sajeev
  password: sapsap
security:
  oauth2:
    client:
      client-id: pfs-client
      client-secret: pfs-secret
      access-token-uri: http://192.168.1.205:9999/auth/oauth/token
      user-authorization-uri: http://192.168.1.205:9999/auth/oauth/authorize
    resource:
      user-info-uri: http://192.168.1.205:9999/time
      jwt:
        keyValue: PfS$$$98567
server:
  port: 8080