spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  profiles: pfsprd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dn47gh3y
    maximum-pool-size: 40
    url: jdbc:mysql://localhost:3306/pfsenquiry?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
  data:
    rest:
      basePath: /api
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: us2.smtp.mailhostbox.com
    port: 587
    username: us2.smtp.mailhostbox.com
    password: Ess@hYYXIaN2#hYYXIaN2
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: us2.smtp.mailhostbox.com
  activiti:
    activiti5CompatibilityEnabled: true
    mail-server-host: us2.smtp.mailhostbox.com
    mail-server-port: 587
    mail-server-user-name: portal.admin@pfs-ess.com
    mail-server-password: Ess@hYYXIaN2#hYYXIaN2
    mail-server-default-from: portal.admin@pfs-ess.com
    mail-server-use-tls: true
    database-schema-update: true
oauth:
  baseUrl: https://enquiry.pfs-ess.com/auth
sap:
  postUrl: http://192.168.1.205:8000/sap/opu/odata/sap/ZPFS_LMS_ENQ_PORTAL_LOAN_V2_SRV/LoanApplicationSet?sap-client=300
  sanctionLetterUrl: http://192.168.1.205:8000/sap/opu/odata/sap/ZPFS_LMS_ENQ_PORTAL_LOAN_V2_SRV/SanctionLetterSet?sap-client=300
  sanctionDocumentUrl: http://192.168.1.205:8000/sap/opu/odata/sap/ZPFS_LMS_ENQ_PORTAL_LOAN_V2_SRV/DocumentSet?sap-client=300
  baseUrl: http://192.168.1.205:8000
  serviceUri: /sap/opu/odata/sap/ZPFS_LOAN_ENQ_PORTAL_SRV/LoanApplicationSet
  monitorServiceUri: /sap/opu/odata/sap/ZPFS_LMS_MONITOR_V1_SRV/
  appraisalServiceUri: /sap/opu/odata/sap/ZPFS_LMS_APPRAISAL_SRV/
  appraisalDocumentUri: /sap/opu/odata/sap/ZPFS_LMS_APPRAISAL_SRV/DocumentSet
  lieUri: /sap/opu/odata/sap/ZPFS_LMS_MONITOR_V1_SRV/LendersIndependentEngineerSet
  lieReportAndFeeUri: /sap/opu/odata/sap/ZPFS_LMS_MONITOR_V1_SRV/LIEReportAndFeeSet
  monitorDocumentUri: /sap/opu/odata/sap/ZPFS_LMS_MONITOR_V1_SRV/DocumentSet
  client: 500
  userName: SAP_PFS_GW
  password: Sapsap@4646
security:
  oauth2:
    client:
      client-id: pfs-client
      client-secret: pfs-secret
      access-token-uri: https://enquiry.pfs-ess.com/auth/oauth/token
      user-authorization-uri: https://enquiry.pfs-ess.com/auth/oauth/authorize
    resource:
      userInfoUri: https://enquiry.pfs-ess.com/auth/api/me
    jwt:
        keyValue: PfS$$$98567
server:
  port: 8080
riskRating:
  baseUrl: http://enquiry.pfs-ess.com:8090/risk/api
batch:
  loanApplicationsScheduledTask: 50000
  loanMonitoringScheduledTask: 50000
  loanAppraisalScheduledTaskCreateAndChange:  50000
  loanAppraisalScheduledTaskDelete:  50000
  loanAppraisalScheduledTaskUpdateLoanPartner : 5000000
  loanAppraisalScheduledTaskUpdateLoanContractId: 5000000
  updateMainLoanPartner: 5000000
  initialDelay: 10000