spring:
  profiles: pfsprd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dn47gh3y
    maximum-pool-size: 40
    url: jdbc:mysql://localhost:3306/pfsenquiry?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
  data:
    rest:
      basePath: /api
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.office365.com
    port: 587
    username: pfs_sapadmin@ptcfinancial.com
    password: PFSsapadmin@5674
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.office365.com
oauth:
  baseUrl: http://192.168.1.247:9999/auth/
sap:
  postUrl: http://192.168.1.207:8000/sap/opu/odata/sap/ZPFS_LOAN_ENQ_PORTAL_SRV/LoanApplicationSet?sap-client=500
  baseUrl: http://192.168.1.207:8000
  serviceUri: /sap/opu/odata/sap/ZPFS_LOAN_ENQ_PORTAL_SRV/LoanApplicationSet
  client: 500
  userName: SAP_PFS_GW
  password: Sapsap@4646
security:
  oauth2:
    client:
      client-id: pfs-client
      client-secret: pfs-secret
      access-token-uri: http://192.168.1.247:9999/auth/oauth/token
      user-authorization-uri: http://192.168.1.247:9999/auth/oauth/authorize
    resource:
      user-info-uri: http://192.168.1.247:9999/auth/time
    jwt:
        keyValue: PfS$$$98567
server:
  port: 8080
