spring:
  profiles:
    active: oauth
  application:
      name: lms-enquiry
server:
  servlet:
    context-path: /enquiry
#logging:
#  file:
#    max-size: 1000 MB
#  level:
#    root: debug
#  path: C:\Users\admin\log\log.txt