export const statesOfIndia = [
    {code: "01" , value:"Andhra Pradesh"},
    {code: "02" , value:"Arunachal Pradesh"},
    {code: "03" , value:"Assam"},
    {code: "04" , value:"Bihar"},
    {code: "05" , value:"Goa"},
    {code: "06" , value:"Gujarat"},
    {code: "07" , value:"Haryana"},
    {code: "08" , value:"Himachal Pradesh"},
    {code: "09" , value:"Jammu und Kashmir"},
    {code: "10" , value:"Karnataka"},
    {code: "11" , value:"Kerala"},
    {code: "12" , value:"Madhya Pradesh"},
    {code: "13" , value:"Maharashtra"},
    {code: "14" , value:"Manipur"},
    {code: "15" , value:"Megalaya"},
    {code: "16" , value:"Mizoram"},
    {code: "17" , value:"Nagaland"},
    {code: "18" , value:"Orissa"},
    {code: "19" , value:"Punjab"},
    {code: "20" , value:"Rajasthan"},
    {code: "21" , value:"Sikkim"},
    {code: "22" , value:"Tamil Nadu"},
    {code: "23" , value:"Tripura"},
    {code: "24" , value:"Uttar Pradesh"},
    {code: "25" , value:"West Bengal"},
    {code: "26" , value:"Andaman and Nicobar Islands"},
    {code: "27" , value:"Chandigarh"},
    {code: "28" , value:"Dadra and Nagar Haveli"},
    {code: "29" , value:"Daman and Diu"},
    {code: "30" , value:"Delhi"},
    {code: "31" , value:"Lakshadweep"},
    {code: "32" , value:"Pondicherry"},
    {code: "33" , value:"Chhaattisgarh"},
    {code: "34" , value:"Jharkhand"},
    {code: "35" , value:"Uttaranchal"},
    {code: "36" , value:"Telangana"}
];

export const collateralTypes = [
    { code: "Z00007", value: "PFS:Personal Guarantee" },
    { code: "Z00008", value: "PFS:Corporate Guarantee" },
    { code: "Z00009", value: "PFS:Bank Guarantee" },
    { code: "Z30001", value: "Securities" },
    { code: "ZCL001", value: "DSRA Account" },
    { code: "ZCL002", value: "TRA Account" },
    { code: "ZCL003", value: "Other Current Assets" },
    { code: "ZDE001", value: "Plant and Machinery" },
    { code: "ZDE002", value: "Furniture and Fixtures" },
    { code: "ZDE003", value: "Office Equipment" },
    { code: "ZDE004", value: "Other Movables" },
    { code: "ZIN002", value: "Inventory" },
    { code: "ZOT001", value: "Project Clearances" },
    { code: "ZOT002", value: "Project Documents" },
    { code: "ZOT003", value: "Bank Guarantees under project documents" },
    { code: "ZOT004", value: "Approvals" },
    { code: "ZOT005", value: "Claims from Insurances" },
    { code: "ZOT006", value: "Claims from letter of credit" },
    { code: "ZPA001", value: "Patents" },
    { code: "ZRE001", value: "Land" },
    { code: "ZRE002", value: "Building" }
];
