package pfs.lms.enquiry.businesspartner.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import pfs.lms.enquiry.businesspartner.domain.AmendmentReason;
import pfs.lms.enquiry.businesspartner.domain.BupaRoleCustomerFieldValues;
import pfs.lms.enquiry.businesspartner.repository.AmendmentReasonRepository;
import pfs.lms.enquiry.businesspartner.repository.BupaRoleCustomerFieldValuesRepository;

@Slf4j
@Component
@RequiredArgsConstructor
public class BuapRoleCustomerFieldValuesConfig implements CommandLineRunner {

    private final BupaRoleCustomerFieldValuesRepository bupaRoleCustomerFieldValuesRepository;
 
    @Override
    public void run(String... strings) throws Exception {

        BupaRoleCustomerFieldValues bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues();


        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0110","0001");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(1,"TR0110","0001","21000000","PFS","A1","T","SBI01",false,"001","001","001");}
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0100","0001");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(2,"TR0100","0001","21000000","PFS","A1","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0101","0001");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(3,"TR0101","0001","21000000","PFS","A1","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0120","0001");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(4,"TR0120","0001","21000000","PFS","A1","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0151","0002");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(5,"TR0151","0002","21000020","PFS","A2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM012","0003");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(6,"ZLM012","0003","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM027","0003");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(7,"ZLM027","0003","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLVN00","0003");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(8,"FLVN00","0003","10800000","PFS","E2","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLVN00","0004");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(9,"FLVN00","0004","10800010","PFS","E3","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLVN00","0005");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(10,"FLVN00","0005","10800020","PFS","E4","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLVN00","0006");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(11,"FLVN00","0006","10800030","PFS","E5","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLVN00","0007");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(12,"FLVN00","0007","10800040","PFS","E6","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("BUP003","0008");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(13,"BUP003","0008","10800060","PFS","E8","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM014","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(14,"ZLM014","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM033","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(15,"ZLM033","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM034","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(16,"ZLM034","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM032","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(17,"ZLM032","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM013","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(18,"ZLM013","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM010","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(19,"ZLM010","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM031","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(20,"ZLM031","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM030","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(21,"ZLM030","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM028","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(22,"ZLM028","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM024","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(23,"ZLM024","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM035","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(24,"ZLM035","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM018","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(25,"ZLM018","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM037","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(26,"ZLM037","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM022","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(27,"ZLM022","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM036","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(28,"ZLM036","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM019","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(29,"ZLM019","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM023","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(30,"ZLM023","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM041","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(31,"ZLM041","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM042","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(32,"ZLM042","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM043","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(33,"ZLM043","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM044","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(34,"ZLM044","0009","10800060","PFS","E8","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("BUP003","0009");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(35,"BUP003","0009","10800060","PFS","E8","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLCU00","0010");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(36,"FLCU00","0010","21000010","PFS","A3","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("FLCU00","0011");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(37,"FLCU00","0011","21000080","PFS","A4","T","SBI01",true,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM002","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(38,"ZLM002","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM003","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(39,"ZLM003","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM004","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(40,"ZLM004","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM005","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(41,"ZLM005","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM006","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(42,"ZLM006","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM007","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(43,"ZLM007","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM008","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(44,"ZLM008","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM009","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(45,"ZLM009","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM011","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(46,"ZLM011","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0200","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(47,"TR0200","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0113","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(48,"TR0113","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0115","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(49,"TR0115","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("TR0121","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(50,"TR0121","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM001","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(51,"ZLM001","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM015","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(52,"ZLM015","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM016","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(53,"ZLM016","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM025","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(54,"ZLM025","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM026","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(55,"ZLM026","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM029","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(56,"ZLM029","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM038","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(57,"ZLM038","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM038","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(58,"ZLM038","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM020","0013");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(59,"ZLM020","0013","10800000","PFS","E2","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM021","0014");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(60,"ZLM021","0014","21000140","PFS","E7","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM040","0015");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(61,"ZLM040","0015","21000130","PFS","E7","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM017","0016");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(62,"ZLM017","0016","21000140","PFS","A4","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);
        bupaRoleCustomerFieldValues = bupaRoleCustomerFieldValuesRepository.findByBupaRoleCodeAndPartnerGroup("ZLM017","0017");if (bupaRoleCustomerFieldValues == null){ bupaRoleCustomerFieldValues = new BupaRoleCustomerFieldValues(63,"ZLM017","0017","21000140","PFS","A4","T","SBI01",false,"001","001","001");}bupaRoleCustomerFieldValuesRepository.save(bupaRoleCustomerFieldValues);





    }
}