package pfs.lms.enquiry.businesspartner.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import pfs.lms.enquiry.businesspartner.domain.BupaRoleEntityFieldStatus;
import pfs.lms.enquiry.businesspartner.domain.BupaRoleEntitySetFieldStatus;
import pfs.lms.enquiry.businesspartner.repository.BupaRoleEntityFieldStatusRepository;
import pfs.lms.enquiry.businesspartner.repository.BupaRoleEntitySetFieldStatusRepository;

@Slf4j
@Component
@RequiredArgsConstructor
public class BupaRoleEntitySetFieldStatusConfig implements CommandLineRunner {

    private final BupaRoleEntitySetFieldStatusRepository bupaRoleEntitySetFieldStatusRepository;

    @Override
    public void run(String... strings) throws Exception {

        BupaRoleEntitySetFieldStatus entitySetFieldStatus = new BupaRoleEntitySetFieldStatus();


        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00001",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00001",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00001",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00001",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00001",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00001",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00001");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00001",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00002",true,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00002",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00002",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00002",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00002",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00002",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00002");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00002",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00004",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00004",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00004",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00004",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00004",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00004",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00004");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00004",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00005",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00005",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00005",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00005",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00005",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00005",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00005");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00005",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00006",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00006",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00006",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00006",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00006",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00006",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00006");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00006",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00009",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00009",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00009",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00009",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00009",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00009",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00009");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00009",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00010",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00010",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00010",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00010",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00010",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00010",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00010");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00010",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00011",true,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00011",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00011",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00011",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00011",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00011",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00011");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00011",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00012",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00012",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00012",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00012",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00012",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00012",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00012");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00012",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationCategoryCode","Z00013",true,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","BusinessPartnerIdentificationNumber;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idInstitute;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idInstitute;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idEntryDate;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idEntryDate;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidFromDate;","Z00013",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","idValidToDate;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","idValidToDate;","Z00013",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","country;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","country;","Z00013",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","countryIso;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","countryIso;","Z00013",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","region;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","region;","Z00013",false,1);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","fileReference;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","fileReference;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentName;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentName;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);
        entitySetFieldStatus = bupaRoleEntitySetFieldStatusRepository.findByBupaRoleCodeAndEntitySetAndFieldNameAndKeyFieldValue("TR0100","BusinessPartnerIdentification","documentType;","Z00013");if (entitySetFieldStatus == null) { entitySetFieldStatus = new BupaRoleEntitySetFieldStatus(null, "TR0100","BusinessPartnerIdentification","documentType;","Z00013",false,2);}bupaRoleEntitySetFieldStatusRepository.save(entitySetFieldStatus);



    }
        }

