package pfs.lms.enquiry.businesspartner.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import pfs.lms.enquiry.businesspartner.domain.BusinessPartnerRoleTypePartnerGroup;
import pfs.lms.enquiry.businesspartner.domain.PartnerGroup;
import pfs.lms.enquiry.businesspartner.repository.BusinessPartnerRoleTypePartnerGroupRepository;
import pfs.lms.enquiry.businesspartner.repository.PartnerGroupRepository;

@Slf4j
@Component
@RequiredArgsConstructor
public class BusinessPartnerRoleTypePartnerGroupConfig implements CommandLineRunner {

    private final BusinessPartnerRoleTypePartnerGroupRepository businessPartnerRoleTypePartnerGroupRepository;
 
    @Override
    public void run(String... strings) throws Exception {
        
        BusinessPartnerRoleTypePartnerGroup businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup();

//        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0001","TR0100");
//        if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(1,"0001","TR0100"); businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }

        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0001","TR0110");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(1,"0001","TR0110");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0001","TR0100");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(2,"0001","TR0100");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0001","TR0101");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(3,"0001","TR0101");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0001","TR0120");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(4,"0001","TR0120");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0002","TR0151");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(6,"0002","TR0151");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0003","ZLM012");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(8,"0003","ZLM012");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0003","ZLM027");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(9,"0003","ZLM027");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0003","FLVN00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(10,"0003","FLVN00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0004","FLVN00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(12,"0004","FLVN00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0005","FLVN00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(14,"0005","FLVN00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0006","FLVN00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(16,"0006","FLVN00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0007","FLVN00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(18,"0007","FLVN00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0008","BUP003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(20,"0008","BUP003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM014");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(22,"0009","ZLM014");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM033");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(23,"0009","ZLM033");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM034");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(24,"0009","ZLM034");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM032");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(25,"0009","ZLM032");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(26,"0009","ZLM013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM010");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(27,"0009","ZLM010");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM031");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(28,"0009","ZLM031");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM030");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(29,"0009","ZLM030");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM028");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(30,"0009","ZLM028");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM024");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(31,"0009","ZLM024");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM035");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(32,"0009","ZLM035");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM018");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(33,"0009","ZLM018");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM037");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(34,"0009","ZLM037");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM022");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(35,"0009","ZLM022");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM036");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(36,"0009","ZLM036");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM019");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(37,"0009","ZLM019");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM023");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(38,"0009","ZLM023");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM041");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(39,"0009","ZLM041");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM042");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(40,"0009","ZLM042");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM043");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(41,"0009","ZLM043");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","ZLM044");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(42,"0009","ZLM044");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0009","BUP003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(43,"0009","BUP003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0010","FLCU00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(45,"0010","FLCU00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0011","FLCU00");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(47,"0011","FLCU00");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM002");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(49,"0013","ZLM002");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(50,"0013","ZLM003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM004");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(51,"0013","ZLM004");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM005");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(52,"0013","ZLM005");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM006");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(53,"0013","ZLM006");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM007");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(54,"0013","ZLM007");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM008");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(55,"0013","ZLM008");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(56,"0013","ZLM009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM011");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(57,"0013","ZLM011");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","TR0200");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(58,"0013","TR0200");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","TR0113");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(59,"0013","TR0113");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","TR0115");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(60,"0013","TR0115");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","TR0121");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(61,"0013","TR0121");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM001");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(62,"0013","ZLM001");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM015");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(63,"0013","ZLM015");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM016");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(65,"0013","ZLM016");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM025");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(66,"0013","ZLM025");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM026");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(67,"0013","ZLM026");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM029");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(68,"0013","ZLM029");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM038");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(69,"0013","ZLM038");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM038");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(70,"0013","ZLM038");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0013","ZLM020");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(71,"0013","ZLM020");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0014","ZLM021");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(72,"0014","ZLM021");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0015","ZLM040");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(73,"0015","ZLM040");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("0016","ZLM017");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(74,"0016","ZLM017");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }



        return;
    }
}