package pfs.lms.enquiry.businesspartner.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import pfs.lms.enquiry.businesspartner.domain.BusinessPartnerRoleTypePartnerGroup;
import pfs.lms.enquiry.businesspartner.domain.PartnerGroup;
import pfs.lms.enquiry.businesspartner.repository.BusinessPartnerRoleTypePartnerGroupRepository;
import pfs.lms.enquiry.businesspartner.repository.PartnerGroupRepository;

@Slf4j
@Component
@RequiredArgsConstructor
@Order(3)
public class BusinessPartnerRoleTypePartnerGroupConfig implements CommandLineRunner {

    private final BusinessPartnerRoleTypePartnerGroupRepository businessPartnerRoleTypePartnerGroupRepository;
 
    @Override
    public void run(String... strings) throws Exception {
        
        BusinessPartnerRoleTypePartnerGroup businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup();
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0110","0001");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(1,"TR0110","0001");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0100","0001");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(2,"TR0100","0001");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0101","0001");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(3,"TR0101","0001");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0120","0001");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(4,"TR0120","0001");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0151","0002");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(5,"TR0151","0002");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM012","0003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(6,"ZLM012","0003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM027","0003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(7,"ZLM027","0003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLVN00","0003");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(8,"FLVN00","0003");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLVN00","0004");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(9,"FLVN00","0004");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLVN00","0005");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(10,"FLVN00","0005");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLVN00","0006");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(11,"FLVN00","0006");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLVN00","0007");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(12,"FLVN00","0007");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("BUP003","0008");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(13,"BUP003","0008");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM014","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(14,"ZLM014","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM033","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(15,"ZLM033","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM034","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(16,"ZLM034","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM032","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(17,"ZLM032","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM013","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(18,"ZLM013","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM010","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(19,"ZLM010","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM031","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(20,"ZLM031","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM030","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(21,"ZLM030","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM028","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(22,"ZLM028","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM024","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(23,"ZLM024","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM035","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(24,"ZLM035","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM018","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(25,"ZLM018","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM037","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(26,"ZLM037","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM022","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(27,"ZLM022","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM036","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(28,"ZLM036","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM019","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(29,"ZLM019","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM023","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(30,"ZLM023","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM041","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(31,"ZLM041","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM042","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(32,"ZLM042","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM043","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(33,"ZLM043","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM044","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(34,"ZLM044","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("BUP003","0009");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(35,"BUP003","0009");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLCU00","0010");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(36,"FLCU00","0010");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("FLCU00","0011");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(37,"FLCU00","0011");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM002","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(38,"ZLM002","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM003","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(39,"ZLM003","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM004","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(40,"ZLM004","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM005","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(41,"ZLM005","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM006","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(42,"ZLM006","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM007","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(43,"ZLM007","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM008","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(44,"ZLM008","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM009","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(45,"ZLM009","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM011","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(46,"ZLM011","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0200","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(47,"TR0200","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0113","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(48,"TR0113","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0115","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(49,"TR0115","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("TR0121","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(50,"TR0121","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM001","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(51,"ZLM001","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM015","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(52,"ZLM015","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM016","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(53,"ZLM016","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM025","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(54,"ZLM025","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM026","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(55,"ZLM026","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM029","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(56,"ZLM029","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM038","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(57,"ZLM038","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM038","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(58,"ZLM038","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM020","0013");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(59,"ZLM020","0013");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM021","0014");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(60,"ZLM021","0014");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM040","0015");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(61,"ZLM040","0015");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM017","0016");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(62,"ZLM017","0016");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }
        businessPartnerRoleTypePartnerGroup = businessPartnerRoleTypePartnerGroupRepository.findByRoleTypeAndPartnerGroup("ZLM018","0017");if (businessPartnerRoleTypePartnerGroup == null){ businessPartnerRoleTypePartnerGroup = new BusinessPartnerRoleTypePartnerGroup(63,"ZLM017","0017");businessPartnerRoleTypePartnerGroupRepository.save(businessPartnerRoleTypePartnerGroup); }

        return;
    }
}